### ISSUE TITLE
Multi Arch builds to support macOS, ARM based linux devices

### ISSUE THREAD

**Issue by adyanth** [kieraneglin/pinchflat#104]
Currently, the pipeline only builds x64 images, which do not run on (at least natively) on ARM devices. You could make use of buildx to use different runner images for different architectures and combine the images under one manifest.

More info here: https://docs.docker.com/build/ci/github-actions/multi-platform/

https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54

**Comment by nothing2obvi** [comment]
I'd like to try this on Docker Desktop for Mac but can't for this reason.

**Comment by adyanth** [comment]
You can run `docker run --platform=linux/x86_64 ...` to use rosetta but that seems to crash the app for me.

**Comment by adyanth** [comment]
Maybe this should also be a bug. I'll attach the stack trace in case it helps (when running as shown above on M1 Pro MacBook Pro)

```log
❯ docker run --platform=linux/x86_64 -v `pwd`/config:/config -v `pwd`/downloads:/downloads -p 8945:8945 keglin/pinchflat:latest
23:03:42.290 [error] Exqlite.Connection (#PID<0.132.0>) failed to connect: ** (Exqlite.Error) database is locked
** (ArgumentError) could not call Module.put_attribute/3 because the module Pinchflat.Repo.Migrations.CreateMediaProfiles is already compiled
    (elixir 1.16.2) lib/module.ex:2360: Module.assert_not_readonly!/2
    (elixir 1.16.2) lib/module.ex:2041: Module.__put_attribute__/5
    /app/lib/pinchflat-0.1.0-alpha.8/priv/repo/migrations/20240123174417_create_channels.exs:2: (module)
23:03:44.793 [notice] Application pinchflat exited: Pinchflat.Application.start(:normal, []) returned an error: shutdown: failed to start child: Pinchflat.Boot.PreJobStartupTasks
    ** (EXIT) an exception was raised:
        ** (Exqlite.Error) no such table: settings
SELECT s0."id", s0."name", s0."value", s0."datatype", s0."inserted_at", s0."updated_at" FROM "settings" AS s0 WHERE (s0."name" = ?)
            (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
            (ecto 3.11.1) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
            (ecto 3.11.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
            (ecto 3.11.1) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
            (pinchflat 0.1.0-alpha.8) lib/pinchflat/settings/settings.ex:62: Pinchflat.Settings.fetch!/3
            (pinchflat 0.1.0-alpha.8) lib/pinchflat/boot/pre_job_startup_tasks.ex:42: Pinchflat.Boot.PreJobStartupTasks.apply_default_settings/0
            (pinchflat 0.1.0-alpha.8) lib/pinchflat/boot/pre_job_startup_tasks.ex:34: Pinchflat.Boot.PreJobStartupTasks.init/1
Kernel pid terminated (application_controller) ("{application_start_failure,pinchflat,{{shutdown,{failed_to_start_child,'Elixir.Pinchflat.Boot.PreJobStartupTasks',{#{message => <<\"no such table: settings\">>,'__struct__' => 'Elixir.Exqlite.Error','__exception__' => true,statement => <<\"SELECT s0.\\"id\\", s0.\\"name\\", s0.\\"value\\", s0.\\"datatype\\", s0.\\"inserted_at\\", s0.\\"updated_at\\" FROM \\"settings\\" AS s0 WHERE (s0.\\"name\\" = ?)\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,1054},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Adapters.SQL',execute,6,[{file,\"lib/ecto/adapters/sql.ex\"},{line,952}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,\"lib/ecto/repo/queryable.ex\"},{line,232}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,19}]},{'Elixir.Ecto.Repo.Queryable',one,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,154}]},{'Elixir.Pinchflat.Settings','fetch!',3,[{file,\"lib/pinchflat

Crash dump is being written to: erl_crash.dump...done
```

**Comment by kieraneglin** [comment]
@adyanth I'll check this out! I develop on an M1 Mac and I had similar issues to what you're seeing when I attempted to cross-compile. I think the C NIFs in Elixir are somehow failing to compile, but I don't know _how_ that would happen. I'll dig in again sometime this weekend

In any case, I test it locally by building the Docker image myself with `docker build . --file selfhosted.Dockerfile -t keglin/pinchflat:latest` then

```bash
# Be sure to replace /host/path/to/config and /host/path/to/downloads below with
# the paths to the directories you created in step 1
docker run \
  -p 8945:8945 \
  -v /host/path/to/config:/config \
  -v /host/path/to/downloads:/downloads \
  keglin/pinchflat:latest
```

(cc @nothing2obvi)

**Comment by kieraneglin** [comment]
Done! I'm pushing up a new build that'll be done once [this actions run](https://github.com/kieraneglin/pinchflat/actions/runs/8400102052) completes.

Turns out it wasn't a NIF issue like I thought - it was that Qemu lacks features that are required by the Erlang JIT compiler ([link](https://gitlab.com/qemu-project/qemu/-/issues/1034) and [link](https://gitlab.com/qemu-project/qemu/-/issues/1953)). Anyway, should be good to go once that run completes!
