### ISSUE TITLE
Triage: Database file present but not writeable

### ISSUE THREAD

**Issue by TechnoMaverick** [kieraneglin/pinchflat#148]
Opening a new issue from #137 , since the locked database ended up changing into this one.

I did delete the contents of the config folder and ended up with this error, which looks very similar to the one I was getting before deleting it:

```
To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:
    config :pinchflat, Pinchflat.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations
The full error report is shown below.
** (Exqlite.Error) Database busy
CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT)
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1161: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:755: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:563: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:432: Ecto.Migrator.run/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    nofile:1: (file)
13:47:05.353 [notice] Application pinchflat exited: Pinchflat.Application.start(:normal, []) returned an error: shutdown: failed to start child: Pinchflat.Boot.PreJobStartupTasks
    ** (EXIT) an exception was raised:
        ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2000ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
See DBConnection.start_link/2 for more information
            (ecto_sqlite3 0.15.1) lib/ecto/adapters/sqlite3/connection.ex:47: Ecto.Adapters.SQLite3.Connection.prepare_execute/5
            (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:960: Ecto.Adapters.SQL.execute!/5
            (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
            (pinchflat 0.1.5) lib/pinchflat/boot/pre_job_startup_tasks.ex:48: Pinchflat.Boot.PreJobStartupTasks.reset_executing_jobs/0
            (pinchflat 0.1.5) lib/pinchflat/boot/pre_job_startup_tasks.ex:34: Pinchflat.Boot.PreJobStartupTasks.init/1
            (stdlib 5.2) gen_server.erl:980: :gen_server.init_it/2
            (stdlib 5.2) gen_server.erl:935: :gen_server.init_it/6
            (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Kernel pid terminated (application_controller) ("{application_start_failure,pinchflat,{{shutdown,{failed_to_start_child,'Elixir.Pinchflat.Boot.PreJobStartupTasks',{#{message => <<\"connection not available and request was dropped from queue after 2000ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:\n\n  1. Ensuring your database is available and that you can connect to it\n  2. Tracking down slow queries and making sure they are running fast enough\n  3. Increasing the pool_size (although this increases resource consumption)\n  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval\n\nSee DBConnection.start_link/2 for more information\n\">>,reason => queue_timeout,'__struct__' => 'Elixir.DBConnection.ConnectionError','__exception__' => true,severity => error},[{'Elixir.Ecto.Adapters.SQLite3.Connection',prepare_execute,5,[{file,\"lib/ecto/adapters/sqlite3/connection.ex\"},{line,47},{error_info,#{module => 'Elixi
Crash dump is being written to: erl_crash.dump...513:47:07.930 [info] Checking permissions for /config
13:47:07.939 [info] Permissions OK
13:47:07.939 [info] Checking permissions for /downloads
13:47:07.945 [info] Permissions OK
13:47:07.945 [info] Checking permissions for /tmp/pinchflat/data
13:47:07.945 [info] Permissions OK
13:47:07.945 [info] Checking permissions for /config/extras
13:47:07.951 [info] Permissions OK
13:47:07.951 [info] Checking permissions for /config/metadata
13:47:07.958 [info] Permissions OK
13:47:12.326 [error] Could not create schema migrations table. This error usually happens due to the following:
  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)
To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.
To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:
    config :pinchflat, Pinchflat.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations
The full error report is shown below.
** (Exqlite.Error) Database busy
CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT)
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1161: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:755: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:563: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:432: Ecto.Migrator.run/4
    (ecto_sql 3.11.1) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    nofile:1: (file)
13:47:15.048 [notice] Application pinchflat exited: Pinchflat.Application.start(:normal, []) returned an error: shutdown: failed to start child: Pinchflat.Boot.PreJobStartupTasks
    ** (EXIT) an exception was raised:
        ** (Exqlite.Error) no such table: oban_jobs
UPDATE "oban_jobs" AS o0 SET "state" = ? WHERE (o0."state" = 'executing')
            (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
            (pinchflat 0.1.5) lib/pinchflat/boot/pre_job_startup_tasks.ex:48: Pinchflat.Boot.PreJobStartupTasks.reset_executing_jobs/0
            (pinchflat 0.1.5) lib/pinchflat/boot/pre_job_startup_tasks.ex:34: Pinchflat.Boot.PreJobStartupTasks.init/1
            (stdlib 5.2) gen_server.erl:980: :gen_server.init_it/2
            (stdlib 5.2) gen_server.erl:935: :gen_server.init_it/6
            (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
{removed_failing_handler,default}
Logger - error: 
```

**Comment by kieraneglin** [comment]
Hey there! Thanks for splitting this out into a new issue.

I don't have an answer for you but I'm going to spend some time later today trying to replicate your issue. Can you give me some high-level details about your setup again?

- What management layer are you running (Portainer, Synology, etc)
- What type of device is running the Docker container? (Nuc, Raspberry Pi, an old PC, etc)
- Where are you attempting to mount your volumes? (Network share, Local HDD, etc)
- If it's a network share, how is _that_ running? (UnRAID, Raspberry Pi, etc)

I _think_ I remember most of your details but I want to make sure I'm right so I have the best chance of replicating the issue 🤞

**Comment by kieraneglin** [comment]
And also, do you use any other Docker containers that connect to network shares? If so, can you pass along the config for one of them?

**Comment by kieraneglin** [comment]
@TechnoMaverick wait - did you mount the network share to a folder visible to your portainer host? That could explain a lot. It would've been a command something like `sudo mount -o resvport <NFS share> <local folder>` - if you haven't run something like that, please let me know!

**Comment by kieraneglin** [comment]
Thank you for the additional details!

If you have discord and you would be okay doing so, would you be able to screen share with me so we can try and get to the bottom of this? I'm really curious where these issues are coming from because I set up a full portainer deployment + new network share to try and replicate it and I had no success. 

 Let me know either way!

**Comment by kieraneglin** [comment]
Yeah, reddit works great! I'm not sure if I'll be free tomorrow but we'll figure something out

**Comment by kieraneglin** [comment]
Resolved! It was a permissions + NFS issue, but I'm hoping some changes introduced in #157 will improve things
