### ISSUE TITLE
[Triage] <your title here> 

### ISSUE THREAD

**Issue by Iliannnn** [kieraneglin/pinchflat#271]
**Describe the bug**

A newly added video won't open when you click on it.

**To Reproduce**

1. Wait for a new video to download.
2. Go to Media History and click on it.

**Expected behavior**

Display the media page like other videos do.

**Screenshots**

![image](https://github.com/kieraneglin/pinchflat/assets/72648901/7f887fa3-4453-4128-bbe5-9e960a98cad2)

**Additional context**

```
20:13:59.787 [error] #PID<0.2483.0> running PinchflatWeb.Endpoint (connection #PID<0.2482.0>, stream id 1) terminated

Server: pinchflat.xxxxxxxx.xxx:80 (http)

Request: GET /sources/1/media/243

** (exit) an exception was raised:

    ** (FunctionClauseError) no function clause matching in String.split/3

        (elixir 1.16.2) lib/string.ex:478: String.split(nil, "\n", [trim: false])

        (pinchflat 2024.5.24) lib/pinchflat_web/components/custom_components/text_components.ex:72: PinchflatWeb.CustomComponents.TextComponents."break_on_newline (overridable 1)"/1

        (phoenix_live_view 0.20.3) lib/phoenix_live_view/tag_engine.ex:68: Phoenix.LiveView.TagEngine.component/3

        (pinchflat 2024.5.24) lib/pinchflat_web/controllers/media_items/media_item_html/show.html.heex:39: anonymous fn/2 in PinchflatWeb.MediaItems.MediaItemHTML.show/1

        (phoenix_live_view 0.20.3) lib/phoenix_live_view/engine.ex:150: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1

        (phoenix_live_view 0.20.3) lib/phoenix_live_view/engine.ex:166: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/3

        (phoenix_live_view 0.20.3) lib/phoenix_live_view/engine.ex:105: Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/2

        (phoenix_live_view 0.20.3) lib/phoenix_live_view/engine.ex:110: Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/2
```

**Comment by Iliannnn** [comment]
https://youtu.be/A4Wb-FQDfzY

It's because this video doesn't have a description. It's common for this channel.

**Comment by Iliannnn** [comment]
Fixed indeed!
