### ISSUE TITLE
New Error When Trying To Add New Sources

### ISSUE THREAD

**Issue by 2IkHLHB** [kieraneglin/pinchflat#391]
For the last 7 days or so, when trying to add new  sources on Pinchflat, I get the following error.

**Status**:
`500`

**Reason**:
`%CaseClauseError{term: {:error, %Jason.DecodeError{position: 0, token: nil, data: ""}}}`

**Stacktrace**:
```
    (pinchflat 2024.9.12) lib/pinchflat/sources/sources.ex:185: Pinchflat.Sources.add_source_details_to_changeset/2
    (pinchflat 2024.9.12) lib/pinchflat/sources/sources.ex:78: Pinchflat.Sources.create_source/2
    (pinchflat 2024.9.12) lib/pinchflat_web/controllers/sources/source_controller.ex:75: PinchflatWeb.Sources.SourceController.create/2
    (pinchflat 2024.9.12) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.action/2
    (pinchflat 2024.9.12) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.phoenix_controller_pipeline/2
    (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
    (pinchflat 2024.9.12) lib/pinchflat_web/endpoint.ex:1: PinchflatWeb.Endpoint.plug_builder_call/2
    (pinchflat 2024.9.12) lib/pinchflat_web/endpoint.ex:1: PinchflatWeb.Endpoint.call/2

```

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I'll need the logs in order to best troubleshoot this. Can you please try to add a source (which should fail), then go to Config > App Info > Download Logs and attach those logs here?

**Comment by 2IkHLHB** [comment]
> Hey there! Thanks for the report (:
> 
> I'll need the logs in order to best troubleshoot this. Can you please try to add a source (which should fail), then go to Config > App Info > Download Logs and attach those logs here?

Well, it's working fine again.
No changes made, no restarting needed. It's just working again.

**Comment by kieraneglin** [comment]
Yeah, that can happen sometimes. YouTube is always making changes behind the scenes and sometimes yt-dlp hasn't caught up (yet).

If you see it again, please re-open the issue and attach those logs! I'd be very curious to see what's going on under the hood (:

**Comment by IAmChrisAMA** [comment]
Seems I'm getting this error now. Seems to have happened when adding a new source. It's a playlist I just created on YouTube that I'll fill with content I want to download. Let me know if you need more info.

`**Status**:
`500`

**Reason**:
`%CaseClauseError{term: {:error, %Jason.DecodeError{position: 0, token: nil, data: ""}}}`

**Stacktrace**:
```
    (pinchflat 2024.9.12) lib/pinchflat/sources/sources.ex:185: Pinchflat.Sources.add_source_details_to_changeset/2
    (pinchflat 2024.9.12) lib/pinchflat/sources/sources.ex:78: Pinchflat.Sources.create_source/2
    (pinchflat 2024.9.12) lib/pinchflat_web/controllers/sources/source_controller.ex:75: PinchflatWeb.Sources.SourceController.create/2
    (pinchflat 2024.9.12) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.action/2
    (pinchflat 2024.9.12) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.phoenix_controller_pipeline/2
    (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
    (pinchflat 2024.9.12) lib/pinchflat_web/endpoint.ex:1: PinchflatWeb.Endpoint.plug_builder_call/2
    (pinchflat 2024.9.12) lib/pinchflat_web/endpoint.ex:1: PinchflatWeb.Endpoint.call/2

```
  `

**Comment by kieraneglin** [comment]
@IAmChrisAMA would you mind attaching your logs? There are instructions earlier in the thread (:

**Comment by IAmChrisAMA** [comment]
[Pinchflat logs Oct 2.txt](https://github.com/user-attachments/files/17219001/Pinchflat.logs.Oct.2.txt)

Here you go. @kieraneglin

**Comment by IAmChrisAMA** [comment]
Quick update.
Just noticed this only does it on this one playlist I made. I tried another playlist I made and it works fine. I'll keep testing and see why that is.

**Comment by IAmChrisAMA** [comment]
Another quick update.

I changed the playlist I was trying before and it now works. The playlist only had 1 short in it which might have been the cause for error. I updated to include one normal video instead which seems to work no problem.

**Comment by kieraneglin** [comment]
Good sleuthing - that's _very_ interesting. I'll try and replicate when I have time, but are you able to confirm whether it's that one short specifically that's the issue?

**Comment by IAmChrisAMA** [comment]
I can 100% confirm that creating a playlist with only shorts in it breaks. I created a playlist with 1 short. It didn't work. Added another short, still broken. I added one normal video and it works fine.

**Comment by kieraneglin** [comment]
Thanks for the assist! Looking into it, it appears to be a yt-dlp [issue](https://github.com/yt-dlp/yt-dlp/issues/10936) that's been fixed in the latest release! I'll push a release later today to bump the app's yt-dlp version

**Comment by ping-localhost** [comment]
Just happened to me whilst trying to add `https://www.youtube.com/feed/subscriptions`.

- App Version: 2024.10.2
- yt-dlp Version: 2024.09.27
- Apprise Version: v1.9.0
- System Architecture: x86_64-pc-linux-gnu
- Timezone: UTC

---

```
**Status**:
`500`

**Reason**:
`%CaseClauseError{term: {:error, %Jason.DecodeError{position: 0, token: nil, data: ""}}}`

**Stacktrace**:
    (pinchflat 2024.10.2) lib/pinchflat/sources/sources.ex:185: Pinchflat.Sources.add_source_details_to_changeset/2
    (pinchflat 2024.10.2) lib/pinchflat/sources/sources.ex:78: Pinchflat.Sources.create_source/2
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:76: PinchflatWeb.Sources.SourceController.create/2
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.action/2
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.phoenix_controller_pipeline/2
    (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
    (pinchflat 2024.10.2) lib/pinchflat_web/endpoint.ex:1: PinchflatWeb.Endpoint.plug_builder_call/2
    (pinchflat 2024.10.2) lib/pinchflat_web/endpoint.ex:1: PinchflatWeb.Endpoint.call/2
```

---

[pinchflat-logs-2024-10-06.txt](https://github.com/user-attachments/files/17270020/pinchflat-logs-2024-10-06.txt)
