### ISSUE TITLE
[FR] Run as specific user to avoid permissions issues with media management

### ISSUE THREAD

**Issue by mininimal** [kieraneglin/pinchflat#398]
**Is your feature request related to a problem? Please describe.**
Pinchflat in its own Docker container runs as the user that starts the container (I think).
This creates an issue for my media management stack (Sonarr specifically for Pinchflat) which runs under a specific user that is only allowed access to my media and download folders.
Because the Pinchflat-created folders have different permissions, Sonarr isn't able to rename episodes inside.

**Describe the solution you'd like**
In many of my Docker containers, I'm able to map the user I'd like the container to run as by specifying the UID and GID as environment variables:
```
environment:
    - PUID=1234 #CHANGE_TO_YOUR_UID
    - PGID=98765 #CHANGE_TO_YOUR_GID
```

**Describe alternatives you've considered**
I am specifically speaking from using Container Manager on a Synology NAS, but you can simply update the folder Ownership or Permissions in File Station after Pinchflat makes them. Not difficult at all, but I've forgotten to do this on some folders and could not figure out why Sonarr wasn't playing nice.

**Additional context**
Sonarr logs just for fun:
```
[v4.0.9.2244] System.UnauthorizedAccessException: Access to the path '/data/media/tv/{SHOW_FOLDER}' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at NzbDrone.Common.Disk.DiskProviderBase.CreateFolder(String path) in ./Sonarr.Common/Disk/DiskProviderBase.cs:line 199
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.CreateFolder(String directoryName) in ./Sonarr.Core/MediaFiles/EpisodeFileMovingService.cs:line 240
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.EnsureEpisodeFolder(EpisodeFile episodeFile, Series series, Int32 seasonNumber, String filePath) in ./Sonarr.Core/MediaFiles/EpisodeFileMovingService.cs:line 187
   at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.MoveEpisodeFile(EpisodeFile episodeFile, Series series, List`1 episodes) in ./Sonarr.Core/MediaFiles/EpisodeFileMovingService.cs:line 70
   at NzbDrone.Core.MediaFiles.RenameEpisodeFileService.RenameFiles(List`1 episodeFiles, Series series) in ./Sonarr.Core/MediaFiles/RenameEpisodeFileService.cs:line 122
```

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

The `PUID` and `PGID` approach is popular with LinuxServer images, but it is considered [outdated](https://docs.linuxserver.io/general/understanding-puid-and-pgid/). For Pinchflat, you can use the [Docker `--user` flag](https://docs.docker.com/engine/containers/run/#user) when starting the container to specify the user/group you want the container to run as!

For example, in Unraid I start the container with `--user "99:100"`. These numbers will almost certainly be different for a Synology machine, but I can't recommend what to use since I don't have any experience with those.

---

Just a heads up that this won't be a retroactive change - you'll probably have to update the permissions of the folders Pinchflat has been using before you start using the `--user` flag

**Comment by mininimal** [comment]
For future me, this can be done with `docker-compose` with `user` under the `service` directive, eg:
```
version: '3'
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    user: "1027:65536"
    environment:
{...}
```
