### ISSUE TITLE
App error when trying to setup new source

### ISSUE THREAD

**Issue by mauriceatkinson** [kieraneglin/pinchflat#418]
I tried to setup a new source that will download all new youtube channel content for channels in my subscription list.  I am not sure if this is supported.  However I received an error which stated I should report as an issue.

Here goes....
error as reported in the app gui.

`**Status**:
`500`

**Reason**:
`%CaseClauseError{term: {:error, %Jason.DecodeError{position: 0, token: nil, data: ""}}}`

**Stacktrace**:
```
    (pinchflat 2024.10.2) lib/pinchflat/sources/sources.ex:185: Pinchflat.Sources.add_source_details_to_changeset/2
    (pinchflat 2024.10.2) lib/pinchflat/sources/sources.ex:78: Pinchflat.Sources.create_source/2
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:76: PinchflatWeb.Sources.SourceController.create/2
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.action/2
    (pinchflat 2024.10.2) lib/pinchflat_web/controllers/sources/source_controller.ex:1: PinchflatWeb.Sources.SourceController.phoenix_controller_pipeline/2
    (phoenix 1.7.14) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
    (pinchflat 2024.10.2) lib/pinchflat_web/endpoint.ex:1: PinchflatWeb.Endpoint.plug_builder_call/2
    (pinchflat 2024.10.2) lib/pinchflat_web/endpoint.ex:1: PinchflatWeb.Endpoint.call/2

```
  `

Download log file
[pinchflat-logs-2024-10-18.txt](https://github.com/user-attachments/files/17438188/pinchflat-logs-2024-10-18.txt)

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (: - I was out of cell service for the last week and I'm just catching up on what I've missed

You're right in saying that this isn't a supported behaviour. I've looked into it and I just don't think it's something that `yt-dlp` can accomplish in the way a user would expect. #404 actually also covered this recently and it's on my TODO list to add a better error message for this case!
