### ISSUE TITLE
[Triage] Version v2024.10.2 fresh install fails to start

### ISSUE THREAD

**Issue by loop0** [kieraneglin/pinchflat#424]
**Describe the bug**
As I'm setting up pinchflat to run on my kubernetes cluster it is failing to start the application due to some database connection error.

**To Reproduce**

1. Setup kubernetes
2. Try to deploy using the following manifest

```yml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pinchflat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinchflat
  template:
    metadata:
      name: pinchflat
      labels:
        app: pinchflat
    spec:
      containers:
        - name: pinchflat
          image: ghcr.io/kieraneglin/pinchflat:v2024.10.2
          env:
            - name: TZ
              value: America/New_York
            - name: JOURNAL_MODE
              value: delete
          volumeMounts:
            - name: downloads
              mountPath: /downloads
              subPath: Youtube
            - name: config
              mountPath: /config
              subPath: pinchflat/config
      volumes:
        - name: downloads
          nfs:
            server: 192.168.20.2
            path: /primary/media
        - name: config
          nfs:
            server: 192.168.20.2
            path: /primary/apps
```
3 - Check the pod logs
```sh
kubectl logs pinchflat-56df977b5-2ssw8
2024-10-21 17:49:28.719 [info] | Checking permissions for /config
2024-10-21 17:49:28.723 [info] | Permissions OK
2024-10-21 17:49:28.723 [info] | Checking permissions for /downloads
2024-10-21 17:49:28.725 [info] | Permissions OK
2024-10-21 17:49:28.725 [info] | Checking permissions for /tmp/pinchflat/data
2024-10-21 17:49:28.726 [info] | Permissions OK
2024-10-21 17:49:28.726 [info] | Checking permissions for /config/extras
2024-10-21 17:49:28.728 [info] | Permissions OK
2024-10-21 17:49:28.728 [info] | Checking permissions for /config/metadata
2024-10-21 17:49:28.730 [info] | Permissions OK
2024-10-21 17:49:28.730 [info] | Checking permissions for /etc/elixir_tzdata_data
2024-10-21 17:49:28.731 [info] | Permissions OK
2024-10-21 17:49:32.216 [error] | Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create" for the desired MIX_ENV.

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create", both for the desired MIX_ENV. Alternatively you may
configure Ecto to use another table and/or repository for managing
migrations:

    config :pinchflat, Pinchflat.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2987ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:1078: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.17.0) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
    (ecto_sql 3.12.0) lib/ecto/adapters/sql.ex:1185: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.12.0) lib/ecto/migrator.ex:779: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.12.0) lib/ecto/migrator.ex:563: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.12.0) lib/ecto/migrator.ex:432: Ecto.Migrator.run/4
    (ecto_sql 3.12.0) lib/ecto/migrator.ex:170: Ecto.Migrator.with_repo/3
    nofile:1: (file)
```

**Expected behavior**
Application should start

**Screenshots**

**Diagnostic info**

I can verify my nfs mounts worked as expected because if I go to my NAS and list the config file it is all populated with the following:
```
pinchflat/
pinchflat/config
pinchflat/config/logs
pinchflat/config/logs/pinchflat.log
pinchflat/config/db
pinchflat/config/db/pinchflat.db
pinchflat/config/metadata
pinchflat/config/metadata/.keep
pinchflat/config/.keep
pinchflat/config/extras
pinchflat/config/extras/.keep
```

The following is the pod information:

```sh
Name:             pinchflat-56df977b5-2ssw8
Namespace:        default
Priority:         0
Service Account:  default
Node:             k8s-03/192.168.20.13
Start Time:       Mon, 21 Oct 2024 17:48:40 -0400
Labels:           app=pinchflat
                  pod-template-hash=56df977b5
Annotations:      <none>
Status:           Running
IP:               10.244.2.21
IPs:
  IP:           10.244.2.21
Controlled By:  ReplicaSet/pinchflat-56df977b5
Containers:
  pinchflat:
    Container ID:   containerd://8b01b001a46e48584c9d84ed0409db4232e0226b02c854ff615482c865ca58c6
    Image:          ghcr.io/kieraneglin/pinchflat:v2024.10.2
    Image ID:       ghcr.io/kieraneglin/pinchflat@sha256:f4bb15e8b5465a25529f81b9e11285bd25200c61cbdb7115d4d952ea0d15f70d
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 21 Oct 2024 17:52:38 -0400
      Finished:     Mon, 21 Oct 2024 17:52:45 -0400
    Ready:          False
    Restart Count:  5
    Environment:
      TZ:            America/New_York
      JOURNAL_MODE:  delete
    Mounts:
      /config from config (rw,path="pinchflat/config")
      /downloads from downloads (rw,path="Youtube")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-n9d7w (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  downloads:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    192.168.20.2
    Path:      /primary/media
    ReadOnly:  false
  config:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    192.168.20.2
    Path:      /primary/apps
    ReadOnly:  false
  kube-api-access-n9d7w:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  5m28s                 default-scheduler  Successfully assigned default/pinchflat-56df977b5-2ssw8 to k8s-03
  Normal   Pulled     5m13s                 kubelet            Successfully pulled image "ghcr.io/kieraneglin/pinchflat:v2024.10.2" in 14.786s (14.786s including waiting). Image size: 267841223 bytes.
  Normal   Pulled     5m4s                  kubelet            Successfully pulled image "ghcr.io/kieraneglin/pinchflat:v2024.10.2" in 196ms (196ms including waiting). Image size: 267841223 bytes.
  Normal   Pulled     4m40s                 kubelet            Successfully pulled image "ghcr.io/kieraneglin/pinchflat:v2024.10.2" in 266ms (266ms including waiting). Image size: 267841223 bytes.
  Normal   Created    4m4s (x4 over 5m13s)  kubelet            Created container pinchflat
  Normal   Started    4m4s (x4 over 5m12s)  kubelet            Started container pinchflat
  Normal   Pulled     4m4s                  kubelet            Successfully pulled image "ghcr.io/kieraneglin/pinchflat:v2024.10.2" in 174ms (174ms including waiting). Image size: 267841223 bytes.
  Normal   Pulling    3m7s (x5 over 5m27s)  kubelet            Pulling image "ghcr.io/kieraneglin/pinchflat:v2024.10.2"
  Normal   Pulled     3m6s                  kubelet            Successfully pulled image "ghcr.io/kieraneglin/pinchflat:v2024.10.2" in 206ms (206ms including waiting). Image size: 267841223 bytes.
  Warning  BackOff    16s (x20 over 4m55s)  kubelet            Back-off restarting failed container pinchflat in pod pinchflat-56df977b5-2ssw8_default(aab0fbbc-fca8-49d1-834a-02c251b84b5e)
```

**Comment by kieraneglin** [comment]
Hey there! Thanks for the report (:

I'm almost certain this is caused by the SQLite database being stored on an NFS as opposed to the local filesystem. I've seen people set this up successfully, but it always seems to end up being a can of worms. A few things to check first (keeping in mind that I have very little experience with k8s):

1. If it's possible to move the config directory away from NFS, that's by far the preferred approach
2. Can you confirm the volume is being mounted with NFSv4? I'm sure your host advertises v4, but we need to confirm that the volume is actually being mounted with v4. I think the package you need is `nfs-utils` and the command is `nfsstat -m` or maybe `nfsstat -s`
3. Do you have any other sqlite databases running over NFS? Sonarr/Radarr come to mind

**Comment by loop0** [comment]
You were right! My nfs was mounted as v3, I forgot that I needed to mount using relative paths for v4, and after doing that it is now working! I'm going to close this issue. Thanks!

**Comment by kieraneglin** [comment]
Love to hear that it's fixed! Also, I wanted to pop in to say that you should _probably_ track `:latest` instead of a specific version since I'm frequently making changes/updating yt-dlp in response to changes YouTube makes behind-the-scenes. If you track a specific version things may start acting weird as YouTube's responses change compared to what the app expects 🤙
